reload-message: "&aConfig reloaded."
help-message:
  - "&7&m----------&r &5&lAnchor &7&m----------"
  - "&e/anchor reload &f Reloads the config file"
  - "&e/anchor give [name] [quantity] [level] &fGives an anchor to a player"
  - "&7&m----------------------------"

cant-give-anchor-message: "&fUse: &e/anchor give [name] [quantity] [level]"
total-anchors-user-can-have: 15
cannot-place-more-anchors: "&4You can not have more than %quantity% anchors."
you-dont-own-this-anchor: "&4You don't own this anchor"

anchor:
  title: "&5Anchor Sell"
  current-anchor-info:
    txt: "Info"
    lore: "Show current anchor info"
  player:
    lore: "Show player stats"
  upgrades:
    txt: "Upgrades"
    lore: "Click to show upgrades"
  upgrade-menu:
    title: "&5Anchor Sell - Upgrades"
    current-level:
      txt: "Current level"
      lore: "Show detailed current level"
    upgrade-button:
      txt: "&6&lUpgrade"
      lore: "Upgrade current anchor"
    back: "&cGo back"



anchor-place: "&aNew anchor placed (%coordsX%, %coordsY%, %coordsZ%)"
anchor-break: "&cAnchor removed (%coordsX%, %coordsY%, %coordsZ%)"