reload-message: "&aConfig reloaded."
help-message:
  - "&7&m----------&r &5&lAnchor &7&m----------"
  - "&e/anchor reload &f Reloads the config file"
  - "&e/anchor give [name] [quantity] [level] &fGives an anchor to a player"
  - "&7&m----------------------------"

cant-give-anchor-message: "&fUse: &e/anchor give [name] [quantity] [level]"
total-anchors-user-can-have: 10
safe-anchor-area: 3
radius-error: "&4You can't place anchors too close to each other."
cannot-place-more-anchors: "&4You can not have more than %quantity% anchors."
you-dont-own-this-anchor: "&4You don't own this anchor"


pay-timer-in-minutes: 1

anchor:
  title: "&5Anchor Sell"
  current-anchor-info:
    txt: "Info"
    lore: "Show current anchor info"
  player:
    lore: "Show player stats"
  upgrades:
    txt: "Upgrades"
    lore: "Click to show  upgrades"
  upgrade-menu:
    title: "&5Anchor Sell - Upgrades"
    current-level:
      txt: "Current level"
      lore: "Show detailed current level"
    upgrade-button:
      txt: "&6&lUpgrade"
      lore: "Upgrade current anchor"
    back: "&cGo back"

anchorbuy:
  title: "&5Buy Anchor Sell"
  anchor-info:
    txt: "What is an Anchor Sell?"
    lore:
      - "An Anchor Sell is a block with which"
      - "you can earn money automatically, from"
      - "time to time, by placing it."

anchor-place: "&aNew anchor placed (%coordsX%, %coordsY%, %coordsZ%)"
anchor-break: "&cAnchor removed (%coordsX%, %coordsY%, %coordsZ%)"