name: AnchorSell
version: 1.3.7
main: mc.nightmarephoenix.anchorsell.AnchorSell
api-version: 1.17
depend: [ Vault ]
softdepend: [ WorldGuard, FactionsX ]
authors: [ DadoGamer13, MatiasME ]
description: Minecraft plugin to get money using a Respawn Anchor.
commands:
  anchor:
    description: Buy an anchor
    usage: /anchor
    permission: anchorsell.player
    permission-message: You don't have <permission>