name: AnchorSell
version: 1.4.2
main: mc.nightmarephoenix.anchorsell.AnchorSell
api-version: 1.16
depend: [ Vault, Essentials ]
softdepend: [ WorldGuard ]
authors: [ DadoGamer13, MatiasME ]
description: Minecraft plugin to get money using a Respawn Anchor.
commands:
  anchor:
    description: Display anchor help message
    usage: /anchor