name: AnchorSell
version: 1.0
main: mc.nightmarephoenix.anchorsell.AnchorSell
api-version: 1.16
depend: [ Vault, FactionsX, EssentialsX ]
authors: [ DadoGamer13, MatiasME ]
description: ...
commands:
  anchor:
    description: Buy an anchor sell
    usage: /anchor
    permission: anchorsell.player
    permission-message: You don't have <permission>