version: 0.3.2

##
# AnchorSell plugin
# Authors: DadoGamer13, MatiasME
# Description: Minecraft plugin to get money using a Respawn anchor.
# GitHub: https://github.com/FranciscoDadone/AnchorSell.git
# Discord: Ddd#7413
##


reload-message: "&aSe ha recargado la configuración exitosamente."
help-message:
  - "&7&m----------&r &5&lAnchor &7&m----------"
  - "&e/anchor buy &fPara comprar un anchor."
  - "&e/anchor list &fDa un listado de todos los anchors en su poder."
  - "&e/anchor top [número] &fTop anchors en el servidor."
  - ""
  - "&e/anchor authors"
  - "&7&m----------------------------"

help-message-admin:
  - "&7&m----------&r &5&lAnchor &7&m----------"
  - "&e/anchor reload &f Recarga la configuración."
  - "&e/anchor give [nombre] [cantidad] [nivel] &fDa un anchor al jugador."
  - "&e/anchor list [nombre] &fDa un listado de todos los anchor en su poder."
  - "&e/anchor top [número] &fTop anchors en el servidor."
  - "&e/anchor upgrades &fMuestra el coste para mejorar un anchor."
  - "&e/anchor changeUpgradeMultiplier [multiplicador] &fCambia el multiplicador de mejora, esto afecta al precio de mejora."
  - "&e/anchor changePrice [precio] &fCambia el precio de compra del anchor."
  - "&e/anchor changeSafeZone [zona] &fCambia el radio mínimo donde se pueden poner anchors."
  - "&e/anchor changeTotalAnchorsUserCanHave [número] &fCambia el total de anchors que un usuario puede tener."
  - "&e/anchor getUserFileName [nombre] &fMuestra donde esta la información del usuario."
  - "&e/anchor revalidate [nombre] &fRevalidación de los anchors de un jugador."
  - "&e/anchor particles [all/low/off] &fCambia las partículas de todos los anchors."
  - ""
  - "&e/anchor authors"
  - "&7&m----------------------------"

unknown-command: "&5&lAnchor &7- &fComando desconocido."
no-permissions: "&cNo tienes permisos para hacer esto. (%permissionNode%)"

cant-give-anchor-message: "&fUtilice: &e/anchor give [nombre] [cantidad] [nivel]"
total-anchors-user-can-have: 10

# Distancia mínima para poner un anchor al lado de otro.
safe-anchor-area: 3

# Si es true los anchors van a dar dinero si el chunk está cargado.
pay-if-chunk-is-loaded: false

# Si es false los anchors no van a pagar a los jugadores afk.
pay-afk-players: true

# Si es true, los jugadores pueden romper anchors ajenos.
break-others: true
break-others-message: "&cNo puedes romper el anchor de %player%&c!"

anchor-value: 100000
radius-error: "&4No puedes colocar anchors tan cerca de otros."
cannot-place-more-anchors: "&4No puedes tener mas de %quantity% anchors."
you-dont-own-this-anchor: "&4No eres el dueño de este anchor"

enable-in-worlds:
  - world
  - world1

world-not-enabled-error: "&cLo siento, los anchors no se pueden poner en este mundo :("

# Periodo de tiempo en el cual se les va a pagar a los jugadores.
pay-timer-in-minutes: 15

anchor:
  title: "&5Anchor"
  current-anchor-info:
    txt: "&6&lEste anchor"
    lore:
      - "&eNivel: &f%level% (%oreLevel%&f)"
      - "&eDinero cada 15 minutos: &f$%moneyPer15Minutes%"
      - "&eDinero por minuto: &f$%moneyPerMinute%"
  player:
    lore:
      - "&eDinero disponible:&f %playerBalance%"
      - "&eNumero total de anchors:&f %playerAnchors% / %maxPlayerAnchors%"
      - "&eDinero total obtenido cada 15 minutos: &f%playerMoneyPer15Minutes%"
  upgrades:
    txt: "&6&lMejoras"
    lore:
      - "&eNivel actual:&f %level% (%oreLevel%&f)"
      - "&eSiguiente mejora: &f%nextLevel% (%nextLevelOre%&f)"
      - "&ePrecio: &f$%priceOfUpgrade%"
  upgrade-menu:
    title: "&5Anchor - Mejoras"
    current-level:
      txt: "%currentLevel%"
      lore:
        - "&7&m----------------------------"
        - "&ePrecio: &r$%priceOfUpgrade%"
        - "&7&m----------------------------"
    upgrade-button:
      txt: "&6&lMejora"
      lore: "Mejorar el anchor"
    back: "&cVolver"
    upgrade-success:
      - "&7&m----------&r &5&lAnchor &7&m----------"
      - "&aAnchor mejorado con exito"
      - "%previusLevel% -> %currentLevel%"
      - "&7&m----------------------------"
    upgrade-fail:
      - "&7&m----------&r &5&lAnchor &7&m----------"
      - "&cNo tienes suficiente dinero :("
      - "&7&m----------------------------"

  # Explosion radius break: si ocurre una explosión cerca de un anchor, este se va a romper en ese radio.
  # Para deshabilitarlo, cambiarlo a "0", para ponerlo como minecraft por defecto: "mc-default"
  explosion-radius-break: "3"

  # Upgrade multiplier: es cuento la upgrade va a costar según el dinero que genera el anchor
  # por hora en el siguiente nivel.
  # Ejemplo: "upgrade-multiplier: 8".
  # Dinero por hora en el siguiente nivel: $10.
  # La upgrade va a salir $80.
  upgrade-multiplier: 6

  # Pay modifier: esto modifica cuanto dinero va a dar el anchor cuando pague.
  # La fórmula utilizada para el pago es:
  # f(anchorLevel, pay-modifier) = (0.1 * anchorLevel + anchorLevel^0.8) * 60 * pay-modifier
  # Tabla de Excel para ver cuanto paga un anchor por nivel y según el modificador:
  #   https://docs.google.com/spreadsheets/d/1_bIag4v8MySS50nN3C6WwwLDBdjPWN3zo-AoybdyNVc/edit?usp=sharing
  # En el Excel las celdas "Pay modifier" y "Pay timer" se pueden modificar para ver los cambios.
  # Nota: pay-modifier acepta decimales. ej: 0.2
  pay-modifier: 1

  list:
    first-message: "&7&m----------&r &5&lAnchors &7&m----------"
    last-message: "&7&m-----------------------------"
    message:
      - ""
      - "&eLocalización:&f %location%"
      - "&eNivel: %level%"
      - ""
  cantaccess: "&4Necesitas contacto directo con el anchor para acceder a él."

anchorbuy:
  title: "&5Comprar un anchor"
  anchor-info:
    txt: "¿Qué es un anchor?"
    lore:
      - "&eUn anchor es un bloque del cual"
      - "&epuedes obtener dinero, cada cierto"
      - "&etiempo solo colocándolo."
  buy:
    title: "&5&lComprar un anchor"
    lore: "&ePrecio: &f$%price%"

confirmscreen:
  title: "&5¿Está seguro que quiere comprar un anchor?"
  you-have-an-anchor: "&5Anchor comprado exitosamente."
  you-cant-afford: "&5No tienes suficiente dinero."
  cancel: "&4&lCancelar"
  confirm: "&a&lConfirmar"

anchor-place:
  - "&7&m----------&r &5&lAnchor &7&m----------"
  - "&aNuevo anchor colocado"
  - ""
  - "&eNivel: &f%level%"
  - "&7&m----------------------------"

anchor-break:
  - "&7&m----------&r &5&lAnchor &7&m----------"
  - "&cAnchor removido"
  - ""
  - "&eNivel: &f%level%"
  - "&7&m----------------------------"


paying-message: "&aHas recibido &c$%amount% &ade &5&&lAnchors"

levels:
  1: "&8Carbón"
  2: "&7Hierro"
  3: "&eOro"
  4: "&bDiamante"
  5: "&6&lNETHERITE"
  maxed-out-level: "&c&l¡Nivel máximo!"

# Las opciones de las partículas son: [ all / low / off ]
particles: "all"