version: 0.3.1

##
# AnchorSell plugin
# Authors: DadoGamer13, MatiasME
# Description: Minecraft plugin to get money using a Respawn anchor.
# Github: https://github.com/FranciscoDadone/AnchorSell.git
# Discord: http://bit.ly/nightmarediscord
##


reload-message: "&aSe ha recargado la configuración exitosamente."
help-message:
  - "&7&m----------&r &5&lAnchor &7&m----------"
  - "&e/anchor buy &fPara comprar un anchor."
  - "&e/anchor list &fDa un listado de todos los anchors en su poder."
  - "&e/anchor top [number] &fTop anchors en el servidor."
  - ""
  - "&e/anchor authors"
  - "&7&m----------------------------"

help-message-admin:
  - "&7&m----------&r &5&lAnchor &7&m----------"
  - "&e/anchor reload &f Recarga la configuración."
  - "&e/anchor give [name] [quantity] [level] &fDa un anchor al jugador."
  - "&e/anchor list [username] &fDa un listado de todos los anchor en su poder."
  - "&e/anchor top [number] &fTop anchors en el servidor."
  - "&e/anchor upgrades &fMuestra el coste para mejorar un anchor."
  - "&e/anchor changeUpgradeMultiplier [multiplier] &fCambia el multiplicador de mejora, esto afecta al precio de mejora."
  - "&e/anchor changePrice [price] &fCambia el precio de compra del anchor."
  - "&e/anchor changeSafeZone [zone] &fCambia el radio mínimo donde se pueden poner anchors."
  - "&e/anchor changeTotalAnchorsUserCanHave [number] &fCambia el total de anchors que un usuario puede tener."
  - "&e/anchor getUserFileName [username] &fMuestra donde esta la información del usuario."
  - "&e/anchor revalidate [username] &fRevalidación de los anchors de un jugador."
  - "&e/anchor particles [all/low/off] &fCambia las partículas de todos los anchors."
  - ""
  - "&e/anchor authors"
  - "&7&m----------------------------"

unknown-command: "&5&lAnchor &7- &fComando desconocido."
no-permissions: "&cNo tienes permisos para hacer esto. (%permissionNode%)"

cant-give-anchor-message: "&fUtilice: &e/anchor give [name] [quantity] [level]"
total-anchors-user-can-have: 5
safe-anchor-area: 3
anchor-value: 100000
radius-error: "&4No puedes colocar anchors tan cerca de otros."
cannot-place-more-anchors: "&4No puedes tener mas de %quantity% anchors."
you-dont-own-this-anchor: "&4No eres el dueño de este anchor"

enable-in-worlds:
  - world
  - world1

world-not-enabled-error: "&cLo siento, los anchors no se pueden poner en este mundo :("

pay-timer-in-minutes: 15

anchor:
  title: "&5Anchor"
  current-anchor-info:
    txt: "&6&lEste anchor"
    lore:
      - "&eNivel: &f%level% (%oreLevel%&f)"
      - "&eDinero cada 15 minutos: &f$%moneyPer15Minutes%"
      - "&eDinero por minuto: &f$%moneyPerMinute%"
  player:
    lore:
      - "&eDinero disponible:&f %playerBalance%"
      - "&eNumero total de anchors:&f %playerAnchors% / %maxPlayerAnchors%"
      - "&eDinero total obtenido cada 15 minutos: &f%playerMoneyPer15Minutes%"
  upgrades:
    txt: "&6&lMejoras"
    lore:
      - "&eNivel actual:&f %level% (%oreLevel%&f)"
      - "&eSiguiente mejora: &f%nextLevel% (%nextLevelOre%&f)"
      - "&ePrecio: &f$%priceOfUpgrade%"
  upgrade-menu:
    title: "&5Anchor - Mejoras"
    current-level:
      txt: "%currentLevel%"
      lore:
        - "&7&m----------------------------"
        - "&ePrecio: &r$%priceOfUpgrade%"
        - "&7&m----------------------------"
    upgrade-button:
      txt: "&6&lMejora"
      lore: "Mejorar el anchor"
    back: "&cVolver"
    upgrade-success:
      - "&7&m----------&r &5&lAnchor &7&m----------"
      - "&aAnchor mejorado con exito"
      - "%previusLevel% -> %currentLevel%"
      - "&7&m----------------------------"
    upgrade-fail:
      - "&7&m----------&r &5&lAnchor &7&m----------"
      - "&cNo tienes suficiente dinero :("
      - "&7&m----------------------------"
  explosion-radius-break: "0" # to set as default minecraft, change to "mc-default"
  upgrade-multiplier: 6 # this is how much the upgrade cost depending of the money that the anchor gives per hour in the next level. For example... upgrade-multiplier: 8. Next level reward per hour: 10. The cost of the upgrade will be 80.
  list:
    first-message: "&7&m----------&r &5&lAnchors &7&m----------"
    last-message: "&7&m-----------------------------"
    message:
      - ""
      - "&eLocation:&f %location%"
      - "&eLevel: %level%"
      - ""
  cantaccess: "&4Necesitas contacto directo con el anchor para acceder a el."

anchorbuy:
  title: "&5Comprar un anchor"
  anchor-info:
    txt: "¿Qué es un anchor?"
    lore:
      - "&eUn anchor es un bloque del cual"
      - "&epuedes obtener dinero, cada cierto"
      - "&etiempo solo colocándolo."
  buy:
    title: "&5&lComprar un anchor"
    lore: "&ePrecio: &f$%price%"

confirmscreen:
  title: "&5¿Está seguro que quiere comprar un anchor?"
  you-have-an-anchor: "&5Anchor comprado exitosamente."
  you-cant-afford: "&5No tienes suficiente dinero."
  cancel: "&4&lCancelar"
  confirm: "&a&lConfirmar"

anchor-place:
  - "&7&m----------&r &5&lAnchor &7&m----------"
  - "&aNuevo anchor colocado"
  - ""
  - "&eNivel: &f%level%"
  - "&7&m----------------------------"

anchor-break:
  - "&7&m----------&r &5&lAnchor &7&m----------"
  - "&cAnchor removido"
  - ""
  - "&eNivel: &f%level%"
  - "&7&m----------------------------"


paying-message: "&aHas recibido &c$%amount% &ade &5&&lAnchors"

levels:
  1: "&8Carbon"
  2: "&7Hierro"
  3: "&eOro"
  4: "&bDiamante"
  5: "&6&lNETHERITE"
  maxed-out-level: "&c&l¡Nivel máximo!"

# Las partículas pueden ser [ all / low / off ]
particles: "all"